apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: datalab-crop-yield
  labels:
    app: datalab-crop-yield
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: datalab-crop-yield
    spec:
      containers:
      - name: datalab
        env:
        - name: PROJECT_ID
          value: datalab-crop-yield
        image: gcr.io/earthengine-project/datalab-ee:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: "4"
            memory: 1Gi
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
---

